//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbionHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImageResources")]
        public string ImageResources {
            get {
                return ((string)(this["ImageResources"]));
            }
            set {
                this["ImageResources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ko-KR")]
        public string DefaultLanguageCultureName {
            get {
                return ((string)(this["DefaultLanguageCultureName"]));
            }
            set {
                this["DefaultLanguageCultureName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ko-KR")]
        public string CurrentLanguageCultureName {
            get {
                return ((string)(this["CurrentLanguageCultureName"]));
            }
            set {
                this["CurrentLanguageCultureName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Languages")]
        public string LanguageDirectoryName {
            get {
                return ((string)(this["LanguageDirectoryName"]));
            }
            set {
                this["LanguageDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FullItemInformation.json")]
        public string FullItemInformationFileName {
            get {
                return ((string)(this["FullItemInformationFileName"]));
            }
            set {
                this["FullItemInformationFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/broderickhyman/ao-bin-dumps/master/formatted/it" +
            "ems.json")]
        public string ItemListSourceUrl {
            get {
                return ((string)(this["ItemListSourceUrl"]));
            }
            set {
                this["ItemListSourceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ItemList.json")]
        public string ItemListFileName {
            get {
                return ((string)(this["ItemListFileName"]));
            }
            set {
                this["ItemListFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int UpdateItemListByDays {
            get {
                return ((int)(this["UpdateItemListByDays"]));
            }
            set {
                this["UpdateItemListByDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/broderickhyman/ao-bin-dumps/master/formatted/it" +
            "ems.json")]
        public string DefaultItemListSourceUrl {
            get {
                return ((string)(this["DefaultItemListSourceUrl"]));
            }
            set {
                this["DefaultItemListSourceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int FullItemInformationUpdateCycleDays {
            get {
                return ((int)(this["FullItemInformationUpdateCycleDays"]));
            }
            set {
                this["FullItemInformationUpdateCycleDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoUpdateConfigUrl {
            get {
                return ((string)(this["AutoUpdateConfigUrl"]));
            }
            set {
                this["AutoUpdateConfigUrl"] = value;
            }
        }
    }
}
